---

# All configuration tasks

- name: Check if Shinken initialized
  become: True
  shell: "su - {{ shinken_user_name }} -c '/usr/bin/shinken --init'"
  args:
    creates: "{{ shinken_user_home }}/.shinken.ini"
  register: 'shinken_check_initialize'


- name: Remove default configuration
  become: True
  file:
    dest: "{{ shinken_paths_etc }}"
    state: 'absent'
  when:
    - "{{ shinken_clear_configuration_after_install }}"
    - "{{ shinken_system_packages_install.changed
          or shinken_pip_packages_install.changed }}"


- name: Create configuration folders
  become: True
  file:
    dest: "{{ item }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  with_items: "{{ shinken_path_configuration }}"
  notify: 'Restart Shinken'


- name: Generate main configuration file
  become: True
  template:
    src: "{{ role_path }}/templates/shinken.cfg.j2"
    dest: "{{ shinken_paths_etc }}/shinken.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'


- name: Generate brokers configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/broker.cfg.j2"
    dest: "{{ shinken_paths_etc }}/brokers/{{ item.name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_brokers }}"


- name: Generate schedulers configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/scheduler.cfg.j2"
    dest: "{{ shinken_paths_etc }}/schedulers/{{ item.name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_schedulers }}"


- name: Generate reactionners configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/reactionner.cfg.j2"
    dest: "{{ shinken_paths_etc }}/reactionners/{{ item.name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_reactionners }}"


- name: Generate pollers configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/poller.cfg.j2"
    dest: "{{ shinken_paths_etc }}/pollers/{{ item.name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_pollers }}"


- name: Generate arbiters configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/arbiter.cfg.j2"
    dest: "{{ shinken_paths_etc }}/arbiters/{{ item.name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_arbiters }}"


- name: Generate realms configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/realm.cfg.j2"
    dest: "{{ shinken_paths_etc }}/realms/{{ item.realm_name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_realms }}"


- name: Generate contacts configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/contact.cfg.j2"
    dest: "{{ shinken_paths_etc }}/contacts/{{ item.contact_name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_contacts }}"


- name: Generate contactgroups configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/contactgroup.cfg.j2"
    dest: "{{ shinken_paths_etc ~ '/contactgroups/'
              ~ (item.contactgroup_name | lower) ~ '.cfg' }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_contactgroups }}"


- name: Generate hostgroups configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/hostgroup.cfg.j2"
    dest: "{{ shinken_paths_etc ~ '/hostgroups/'
              ~ (item.hostgroup_name | lower) ~ '.cfg' }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_hostgroups }}"


- name: Generate servicegroups configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/servicegroup.cfg.j2"
    dest: "{{ shinken_paths_etc ~ '/servicegroups/'
              ~ (item.servicegroup_name | lower) ~ '.cfg' }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_servicegroups }}"


- name: Generate timeperiods configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/timeperiod.cfg.j2"
    dest: "{{ shinken_paths_etc ~ '/timeperiods/'
              ~ (item.timeperiod_name | lower) ~ '.cfg' }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_timeperiods }}"


- name: Generate notificationways configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/notificationway.cfg.j2"
    dest: "{{ shinken_paths_etc ~ '/notificationways/'
              ~ (item.notificationway_name | lower) ~ '.cfg' }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_notificationways }}"
