---

# All configuration tasks

- name: Check if Shinken initialized
  become: True
  shell: "su - {{ shinken_user_name }} -c '/usr/bin/shinken --init'"
  args:
    creates: "{{ shinken_user_home }}/.shinken.ini"
  register: 'shinken_check_initialize'


