---

# All configuration tasks

- name: Check if Shinken initialized
  become: True
  shell: "su - {{ shinken_user_name }} -c '/usr/bin/shinken --init'"
  args:
    creates: "{{ shinken_user_home }}/.shinken.ini"
  register: 'shinken_check_initialize'


- name: Remove default configuration
  become: True
  file:
    dest: "{{ shinken_paths_etc }}"
    state: 'absent'
  when:
    - "{{ shinken_clear_configuration_after_install }}"
    - "{{ shinken_system_packages_install.changed
          or shinken_pip_packages_install.changed }}"


- name: Create configuration folders
  become: True
  file:
    dest: "{{ item }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_folders_mode }}"
    state: 'directory'
  with_items: "{{ shinken_path_configuration }}"
  notify: 'Restart Shinken'


- name: Generate main configuration file
  become: True
  template:
    src: "{{ role_path }}/templates/shinken.cfg.j2"
    dest: "{{ shinken_paths_etc }}/shinken.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'


- name: Generate daemons configuration files
  become: True
  template:
    src: "{{ role_path }}/templates/daemon.ini.j2"
    dest: "{{ shinken_paths_etc }}/daemons/{{ (item.pidfile | basename | splitext)[0] }}.ini"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items:
    - "{{ shinken_daemon_defaults | combine(shinken_brokerd) }}"
    - "{{ shinken_daemon_defaults | combine(shinken_pollerd) }}"
    - "{{ shinken_daemon_defaults | combine(shinken_reactionnerd) }}"
    - "{{ shinken_daemon_defaults | combine(shinken_receiverd) }}"
    - "{{ shinken_daemon_defaults | combine(shinken_schedulerd) }}"


- name: Generate brokers definition files
  become: True
  template:
    src: "{{ role_path }}/templates/broker.cfg.j2"
    dest: "{{ shinken_paths_etc }}/brokers/{{ item.broker_name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_brokers }}"


- name: Generate schedulers definition files
  become: True
  template:
    src: "{{ role_path }}/templates/scheduler.cfg.j2"
    dest: "{{ shinken_paths_etc }}/schedulers/{{ item.scheduler_name
              | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_schedulers }}"


- name: Generate reactionners definition files
  become: True
  template:
    src: "{{ role_path }}/templates/reactionner.cfg.j2"
    dest: "{{ shinken_paths_etc }}/reactionners/{{ item.reactionner_name
              | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_reactionners }}"


- name: Generate pollers definition files
  become: True
  template:
    src: "{{ role_path }}/templates/poller.cfg.j2"
    dest: "{{ shinken_paths_etc }}/pollers/{{ item.poller_name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_pollers }}"


- name: Generate arbiters definition files
  become: True
  template:
    src: "{{ role_path }}/templates/arbiter.cfg.j2"
    dest: "{{ shinken_paths_etc }}/arbiters/{{ item.arbiter_name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_arbiters }}"


- name: Generate hosts definition files
  become: True
  template:
    src: "{{ role_path }}/templates/host.cfg.j2"
    dest: "{{ shinken_paths_etc }}/hosts/{{ item.host_name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_hosts }}"


- name: Generate services definition files
  become: True
  template:
    src: "{{ role_path }}/templates/service.cfg.j2"
    dest: "{{ shinken_paths_etc }}/services/{{
              (item.host_name | lower)
              ~ '__' ~ (item.service_description | lower) }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_services }}"


- name: Generate realms definition files
  become: True
  template:
    src: "{{ role_path }}/templates/realm.cfg.j2"
    dest: "{{ shinken_paths_etc }}/realms/{{ item.realm_name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_realms }}"


- name: Generate contacts definition files
  become: True
  template:
    src: "{{ role_path }}/templates/contact.cfg.j2"
    dest: "{{ shinken_paths_etc }}/contacts/{{ item.contact_name | lower }}.cfg"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_contacts }}"


- name: Generate contactgroups definition files
  become: True
  template:
    src: "{{ role_path }}/templates/contactgroup.cfg.j2"
    dest: "{{ shinken_paths_etc ~ '/contactgroups/'
              ~ (item.contactgroup_name | lower) ~ '.cfg' }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_contactgroups }}"


- name: Generate hostgroups definition files
  become: True
  template:
    src: "{{ role_path }}/templates/hostgroup.cfg.j2"
    dest: "{{ shinken_paths_etc ~ '/hostgroups/'
              ~ (item.hostgroup_name | lower) ~ '.cfg' }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_hostgroups }}"


- name: Generate servicegroups definition files
  become: True
  template:
    src: "{{ role_path }}/templates/servicegroup.cfg.j2"
    dest: "{{ shinken_paths_etc ~ '/servicegroups/'
              ~ (item.servicegroup_name | lower) ~ '.cfg' }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_servicegroups }}"


- name: Generate timeperiods definition files
  become: True
  template:
    src: "{{ role_path }}/templates/timeperiod.cfg.j2"
    dest: "{{ shinken_paths_etc ~ '/timeperiods/'
              ~ (item.timeperiod_name | lower) ~ '.cfg' }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_timeperiods }}"


- name: Generate notificationways definition files
  become: True
  template:
    src: "{{ role_path }}/templates/notificationway.cfg.j2"
    dest: "{{ shinken_paths_etc ~ '/notificationways/'
              ~ (item.notificationway_name | lower) ~ '.cfg' }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_notificationways }}"


- name: Generate commands definition files
  become: True
  template:
    src: "{{ role_path }}/templates/command.cfg.j2"
    dest: "{{ shinken_paths_etc ~ '/commands/'
              ~ (item.command_name | lower) ~ '.cfg' }}"
    owner: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    mode: "{{ shinken_config_files_mode }}"
  notify: 'Restart Shinken'
  with_items: "{{ shinken_commands }}"
