---

# All tasks about Shinken installation

- name: Create shinken group
  become: True
  group:
    name: "{{ shinken_user_group }}"
    state: 'present'
    system: False


- name: Create shinken user
  become: True
  user:
    name: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    home: "{{ shinken_user_home }}"
    password: "{{ shinken_user_password }}"
    shell: "{{ shinken_user_shell }}"
    state: 'present'
    system: False
    update_password: "{{ shinken_user_update_password }}"


- name: Install shinken system dependencies
  become: True
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  register: 'shinken_system_packages_install'
  with_items: "{{ shinken_system_dependencies
                    + shinken_system_additional_packages }}"


- name: Install shinken pip packages with specific version
  become: True
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version }}"
  register: 'shinken_pip_packages_install'
  with_items: "{{ shinken_pip_packages + shinken_pip_additional_packages }}"
  when: "{{ item.version is defined }}"


- name: Install shinken pip packages without version
  become: True
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  register: 'shinken_pip_packages_install'
  with_items: "{{ shinken_pip_packages + shinken_pip_additional_packages }}"
  when: "{{ item.version is not defined }}"


- name: Configure daemon start
  become: True
  service:
    name: "shinken-{{ item.key }}"
    enabled: "{{ item.value.enabled }}"
  with_dict: "{{ shinken_daemons }}"


- name: Install additional modules using shinken.io
  become: True
  shell: "su - {{ shinken_user_name }} -c 'shinken install {{ item.name }}'"
  register: 'shinken_modules_install_shinken_io'
  with_items: "{{ shinken_modules }}"
  when: "{{ item.method == 'shinken_io' }}"


- name: Install additional modules using custom method
  include: "{{ role_path }}/tasks/module_installation_{{ item.name }}.yml"
  register: 'shinken_modules_install_custom'
  with_items: "{{ shinken_modules }}"
  when: "{{ item.method == 'custom' }}"


- name: Restart daemon if packages changed
  become: True
  service:
    name: "shinken-{{ item.key }}"
    enabled: "{{ item.value.enabled }}"
    state: 'restarted'
  with_dict: "{{ shinken_daemons }}"
  when:
    - "{{ shinken_system_packages_install.changed
          or shinken_pip_packages_install.changed }}"
    - "{{ item.value.started }}"


- name: Check daemon state is good
  become: True
  service:
    name: "shinken-{{ item.key }}"
    state: "{{ item.value.started | ternary('started', 'stopped') }}"
  with_dict: "{{ shinken_daemons }}"

