---

# All tasks about Shinken installation

- name: Create shinken group
  become: True
  group:
    name: "{{ shinken_user_group }}"
    state: 'present'
    system: False


- name: Create shinken user
  become: True
  user:
    name: "{{ shinken_user_name }}"
    group: "{{ shinken_user_group }}"
    home: "{{ shinken_user_home }}"
    password: "{{ shinken_user_password }}"
    shell: "{{ shinken_user_shell }}"
    state: 'present'
    system: False
    update_password: "{{ shinken_user_update_password }}"


- name: Install shinken system dependencies
  become: True
  package:
    name: "{{ item }}"
    state: "{{ shinken_system_dependencies_state }}"
  register: 'shinken_system_packages_install'
  with_items: "{{ shinken_system_dependencies }}"


- name: Install shinken pip package
  become: True
  pip:
    name: "{{ shinken_pip_package_name }}"
    state: "{{ shinken_pip_package_state }}"
    version: "{{ shinken_pip_package_version }}"
  register: 'shinken_pip_packages_install'


- name: Configure daemon start
  become: True
  service:
    name: "shinken-{{ item.key }}"
    enabled: "{{ item.value.enabled }}"
  with_dict: "{{ shinken_daemons }}"


- name: Stop daemon state is good
  become: True
  service:
    name: "shinken-{{ item.key }}"
    state: "{{ item.value.started | ternary('started', 'stopped') }}"
  with_dict: "{{ shinken_daemons }}"


- name: Restart daemon if packages changed
  become: True
  service:
    name: "shinken-{{ item.key }}"
    enabled: "{{ item.value.enabled }}"
    state: 'restarted'
  with_dict: "{{ shinken_daemons }}"
  when:
    - "{{ shinken_system_packages_install.changed
          or shinken_pip_packages_install.changed }}"
    - "{{ item.value.started }}"

