---

# Main tasks file for shinken role

- name: Load distribution variables
  include_vars: "{{ role_path }}/vars/{{ ansible_distribution | lower }}.yml"
  tags:
    - 'shinken'
    - 'install'


- name: Manage Shinken installation tasks
  include: "{{ role_path }}/tasks/installation.yml"
  tags:
    - 'shinken'
    - 'install'


- name: Manage Shinken configuration tasks
  include: "{{ role_path }}/tasks/configuration.yml"
  tags:
    - 'shinken'
    - 'configuration'


- name: Check daemon state is good
  become: True
  service:
    name: "shinken-{{ item.key }}"
    state: "{{ item.value.started | ternary('started', 'stopped') }}"
  with_dict: "{{ shinken_daemons }}"

