---

# Custom module or pack installation using git

- name: Clone module or pack repository
  become: True
  become_user: "{{ shinken_user_name }}"
  git:
    repo: "{{ item.install.repo }}"
    dest: "{{ item.install.dest | default('/tmp') }}/{{ item.name }}"
    version: "{{ item.install.version | default('HEAD') }}"


# Become_user of previous task should not working as espected :/
- name: Change owner of downloaded module
  become: True
  command: >
    chown -R {{ shinken_user_name }}:{{ shinken_user_name }}
    {{ item.install.dest | default('/tmp') }}/{{ item.name }}


- name: Install module or pack
  become: True
  shell: "su - {{ shinken_user_name }} -c 'shinken install --local {{ item.install.dest | default('/tmp') }}/{{ item.name }}'"
  when: "{{ item.name not in shinken_modules_packs_installed.stdout_lines }}"


- name: Update module or pack
  become: True
  shell: "su - {{ shinken_user_name }} -c 'shinken update --local {{ item.install.dest | default('/tmp') }}/{{ item.name }}'"
  when: "{{ item.name in shinken_modules_packs_installed.stdout_lines }}"


- name: Remove clone
  become: True
  file:
    dest: "{{ item.install.dest | default('/tmp') }}/{{ item.name }}"
    state: 'absent'
