---

# Handlers main file for shinken role

- name: 'Restart Shinken'
  become: True
  service:
    name: "shinken-{{ item.key }}"
    state: 'restarted'
    enabled: "{{ item.value.enabled }}"
  with_dict: "{{ shinken_daemons }}"
  when:
    - item.value.started
  tags:
    - 'role::shinken'
    - 'role::shinken::config'
    - 'role::shinken::init'
    - 'role::shinken::install'
    - 'role::shinken::upgrade_config'
